### PR TITLE
chore: use viewer instead of _viewer

### PR DESCRIPTION
**Pull request by notrab**
Related to https://linear.app/graphcms/issue/ENG-3039#comment-dceaa8ca

### CODE REVIEW

**Review by d-winter — APPROVED** [review]

**Comment by notrab** [comment]
@d-winter how far away is actually removing the field `_viewer` from the Management API? I can release this as a "fix" so it goes out now, or keep it as "chore" which will bundle it into the next release.

**Comment by d-winter** [comment]
There is a draft PR here: https://github.com/GraphCMS/autobahn/pull/2383
So it will take some time because we need to check once more the frontend is not relying on anything we will remove.

**Comment by flexzuu** [comment]
The question is also when we can release the removal of `_viewer` as we still have users of the old skd versions out there in the wild. We should probably wait at least one or two release cycles before removing it. Thats why i removed it from the next batch of deprecated removals.

**Comment by notrab** [comment]
@flexzuu agreed in regards to the API removal. I'll go ahead and merge this, and keep an eye on the PR above.

**Comment by notrab** [comment]
@flexzuu @d-winter it might also be worth adding a `Agent` header with the version of the SDK so we can better track usage for future.

**Comment by d-winter** [comment]
Right now we don't track mgmt api calls in BI. But adding it still makes sense. We can then maybe use it in the current approach tracking user activity from the management server calls.

**Pull request merged**
